"use client";

import { FormEvent, useEffect, useState } from "react";
import { neonClient } from "@/lib/neon";
import { friendlyWorkspaceError, loadWorkspace } from "@/lib/workspace";

function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48);}
export default function OnboardingPage(){
  const [checking,setChecking]=useState(true);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let active=true;void loadWorkspace().then(workspace=>{if(!active)return;if(!workspace){window.location.replace("/sign-in");return;}if(workspace.business){window.location.replace("/");return;}setChecking(false);}).catch(reason=>{if(active){setError(friendlyWorkspaceError(reason));setChecking(false);}});return()=>{active=false};},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;setLoading(true);setError("");const data=new FormData(event.currentTarget);const name=String(data.get("name")||"").trim().replace(/\s+/g," ");const type=String(data.get("business_type")||"services");const document=String(data.get("document")||"").trim();const base=slugify(name);const slug=`${base}-${Math.random().toString(36).slice(2,7)}`;try{if(name.length<2||name.length>120)throw new Error("INVALID_BUSINESS_NAME");if(!base)throw new Error("INVALID_BUSINESS_SLUG");const result=await (neonClient as any).rpc("create_business",{p_name:name,p_slug:slug,p_business_type:type,p_document:document||null});if(result.error)throw result.error;window.localStorage.removeItem("nassus_active_business_id");window.location.replace("/");}catch(reason){setError(friendlyWorkspaceError(reason));}finally{setLoading(false);}}
  if(checking)return <main className="loading"><div className="brand-mark">N</div><h1>Preparando sua empresa...</h1><p>Validando sua conta.</p></main>;
  return <main className="onboarding-page"><section className="onboarding-card"><span className="eyebrow">PRIMEIROS PASSOS</span><h1>Configure sua empresa</h1><p>O workspace nasce no plano Essencial com 2 usuários, até 90 clientes e 7 dias para testar.</p><form onSubmit={submit}><label>Nome da empresa<input name="name" minLength={2} maxLength={120} required placeholder="Ex.: Clínica Bem Estar"/></label><label>Tipo de negócio<select name="business_type" defaultValue="services"><option value="services">Prestador de serviços</option><option value="clinic">Clínica / saúde</option><option value="beauty">Barbearia / salão / estética</option><option value="pet">Petshop / veterinária</option><option value="workshop">Oficina / assistência técnica</option><option value="professional">Profissional liberal</option><option value="other">Outro</option></select></label><label>CPF/CNPJ (opcional)<input name="document" maxLength={40} placeholder="Documento da empresa"/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary auth-submit" disabled={loading}>{loading?"Criando empresa...":"Entrar no Nassus Gestão"}</button></form></section></main>;
}
