"use client";

import { FormEvent, useEffect, useState } from "react";
import AppIcon from "@/components/app-icon";
import { neonClient } from "@/lib/neon";
import { friendlyWorkspaceError, loadWorkspace, waitForWorkspaceReady } from "@/lib/workspace";

function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48);}
export default function OnboardingPage(){
  const [checking,setChecking]=useState(true);const [loading,setLoading]=useState(false);const [stage,setStage]=useState<"idle"|"creating"|"sync">("idle");const [error,setError]=useState("");
  useEffect(()=>{let active=true;void loadWorkspace({sessionAttempts:8,dataAttempts:5}).then(workspace=>{if(!active)return;if(!workspace){window.location.replace("/sign-in");return;}if(workspace.business){window.location.replace("/");return;}setChecking(false);}).catch(reason=>{if(active){setError(friendlyWorkspaceError(reason));setChecking(false);}});return()=>{active=false};},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;setLoading(true);setStage("creating");setError("");const data=new FormData(event.currentTarget);const name=String(data.get("name")||"").trim().replace(/\s+/g," ");const type=String(data.get("business_type")||"services");const document=String(data.get("document")||"").trim();const base=slugify(name);const slug=`${base}-${Math.random().toString(36).slice(2,7)}`;try{if(name.length<2||name.length>120)throw new Error("INVALID_BUSINESS_NAME");if(!base)throw new Error("INVALID_BUSINESS_SLUG");const result=await (neonClient as any).rpc("create_business",{p_name:name,p_slug:slug,p_business_type:type,p_document:document||null});if(result.error)throw result.error;window.localStorage.removeItem("nassus_active_business_id");setStage("sync");await waitForWorkspaceReady();window.location.replace("/");}catch(reason){setStage("idle");setError(friendlyWorkspaceError(reason));}finally{setLoading(false);}}
  if(checking)return <main className="workspace-skeleton"><div className="skeleton-bar"/><div className="skeleton-grid">{[0,1,2,3].map(item=><div className="skeleton-card" key={item}/>)}</div></main>;
  const buttonLabel=stage==="creating"?"Criando workspace...":stage==="sync"?"Preparando seu painel...":"Criar meu workspace";
  return <main className="auth-page onboarding-premium"><section className="auth-visual"><div className="auth-brand"><div className="brand-mark">N</div><div><strong>Nassus Gestão</strong><small>CONFIGURAÇÃO INICIAL</small></div></div><div className="auth-copy"><span className="eyebrow">SEU BUSINESS OS</span><h1>Monte sua operação em minutos.</h1><p>Você começa com uma estrutura limpa e pronta para receber clientes, serviços, agenda, propostas e financeiro.</p><div className="onboarding-steps"><div><span><AppIcon name="briefcase" size={15}/></span><p><strong>1. Empresa</strong><small>Identidade e segmento do workspace.</small></p></div><div><span><AppIcon name="users" size={15}/></span><p><strong>2. Clientes</strong><small>Até 90 cadastros no Essencial.</small></p></div><div><span><AppIcon name="calendar" size={15}/></span><p><strong>3. Operação</strong><small>Agenda, orçamentos e financeiro integrados.</small></p></div></div></div></section><section className="auth-side"><div className="auth-card onboarding-card-one"><div className="auth-card-mark">01</div><span className="eyebrow">PRIMEIRO WORKSPACE</span><h2>Configure sua empresa</h2><p>Essas informações criam a base da sua conta. Você pode ajustar depois.</p><form onSubmit={submit}><label>Nome da empresa<input name="name" minLength={2} maxLength={120} required autoComplete="organization" placeholder="Ex.: Clínica Bem Estar"/></label><label>Tipo de negócio<select name="business_type" defaultValue="services"><option value="services">Prestador de serviços</option><option value="clinic">Clínica / saúde</option><option value="beauty">Barbearia / salão / estética</option><option value="pet">Petshop / veterinária</option><option value="workshop">Oficina / assistência técnica</option><option value="professional">Profissional liberal</option><option value="other">Outro</option></select></label><label>CPF/CNPJ <small className="optional">opcional</small><input name="document" maxLength={40} inputMode="numeric" placeholder="Documento da empresa"/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary auth-submit" disabled={loading}>{buttonLabel}</button>{loading?<div className="auth-progress" aria-hidden="true"><i/></div>:null}</form><div className="onboarding-plan"><span>7 dias de avaliação</span><strong>Essencial • 2 usuários • 90 clientes</strong></div></div></section></main>;
}
