"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { neonClient } from "@/lib/neon";
import { formatDate, formatMoney, friendlyWorkspaceError, requireWorkspace, type Workspace } from "@/lib/workspace";

type Quote={id:string;client_id:string|null;number:number;status:string;subtotal:number|string;discount:number|string;total:number|string;notes:string|null;valid_until:string|null;created_at:string};
type Item={id:string;description:string;quantity:number|string;unit_price:number|string;total:number|string};
type Client={name:string;phone:string|null;email:string|null;document:string|null};

export default function QuotePrintPage(){
  const params=useParams<{id:string}>();const id=String(params?.id||"");
  const [workspace,setWorkspace]=useState<Workspace|null>(null);const [quote,setQuote]=useState<Quote|null>(null);const [items,setItems]=useState<Item[]>([]);const [client,setClient]=useState<Client|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{let active=true;async function load(){try{const current=await requireWorkspace();if(!current||!id||!active)return;const qq=await neonClient.from("quotes").select("id,client_id,number,status,subtotal,discount,total,notes,valid_until,created_at").eq("business_id",current.business.id).eq("id",id).single();if(qq.error)throw qq.error;const q=qq.data as Quote;const [iq,cq]=await Promise.all([neonClient.from("quote_items").select("id,description,quantity,unit_price,total").eq("quote_id",id),q.client_id?neonClient.from("clients").select("name,phone,email,document").eq("business_id",current.business.id).eq("id",q.client_id).single():Promise.resolve({data:null,error:null}) as any]);setWorkspace(current);setQuote(q);setItems((Array.isArray(iq.data)?iq.data:[]) as Item[]);if(!cq.error&&cq.data)setClient(cq.data as Client);}catch(reason){setError(friendlyWorkspaceError(reason));}finally{if(active)setLoading(false);}}void load();return()=>{active=false};},[id]);
  if(loading)return <main className="loading"><div className="brand-mark">N</div><h1>Preparando orçamento...</h1></main>;
  if(!workspace||!quote)return <main className="loading"><h1>Orçamento indisponível</h1><p>{error}</p><a className="primary" href="/orcamentos">Voltar</a></main>;
  const business=workspace.business;return <main className="print-page"><div className="print-actions no-print"><a className="secondary" href="/orcamentos">← Voltar</a><button className="primary" onClick={()=>window.print()}>Imprimir / Salvar PDF</button></div><article className="print-sheet"><header className="print-head"><div><div className="brand-mark" style={{marginBottom:14}}>N</div><h1>{business.name}</h1><p>{business.document||""}</p><p>{business.phone||""} {business.email?`• ${business.email}`:""}</p>{business.address?<p>{business.address}</p>:null}</div><div className="print-meta"><span className="eyebrow">ORÇAMENTO</span><h2>#{quote.number}</h2><p>Emitido em {new Date(quote.created_at).toLocaleDateString("pt-BR")}</p><p>Validade: {formatDate(quote.valid_until)}</p><strong>{({draft:"Rascunho",sent:"Enviado",approved:"Aprovado",rejected:"Recusado",expired:"Expirado",converted:"Convertido"} as Record<string,string>)[quote.status]||quote.status}</strong></div></header><section className="print-client"><div><span className="eyebrow">CLIENTE</span><h3>{client?.name||"Cliente não informado"}</h3><p>{client?.document||""}</p></div><div><p>{client?.phone||""}</p><p>{client?.email||""}</p></div></section><table className="print-table"><thead><tr><th>Descrição</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.description}</td><td>{Number(item.quantity).toLocaleString("pt-BR")}</td><td>{formatMoney(item.unit_price)}</td><td>{formatMoney(item.total)}</td></tr>)}</tbody></table><div className="print-totals"><div className="print-total-row"><span>Subtotal</span><strong>{formatMoney(quote.subtotal)}</strong></div><div className="print-total-row"><span>Desconto</span><strong>- {formatMoney(quote.discount)}</strong></div><div className="print-total-row grand"><span>Total</span><strong>{formatMoney(quote.total)}</strong></div></div>{quote.notes?<section style={{marginTop:35,paddingTop:20,borderTop:"1px solid #ddd"}}><span className="eyebrow">OBSERVAÇÕES E CONDIÇÕES</span><p style={{whiteSpace:"pre-wrap",lineHeight:1.7}}>{quote.notes}</p></section>:null}<footer style={{marginTop:55,paddingTop:18,borderTop:"1px solid #ddd",fontSize:11,color:"#646970",display:"flex",justifyContent:"space-between",gap:15}}><span>Documento gerado pelo Nassus Gestão</span><span>{business.name}</span></footer></article></main>;
}
