"use client";

import { useEffect, useState } from "react";
import { neonClient } from "@/lib/neon";
import { getCurrentUser } from "@/lib/session";
import { formatMoney } from "@/lib/workspace";

type Dashboard={businesses:number;trials:number;active:number;past_due:number;users:number;mrr:number|string};
type Business={id:string;name:string;slug:string;plan:"essential"|"professional";status:string;client_count:number;user_count:number;trial_ends_at:string|null;created_at:string};

export default function AdminPage(){
  const [allowed,setAllowed]=useState<boolean|null>(null);const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [businesses,setBusinesses]=useState<Business[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const user=await getCurrentUser();if(!user?.email){window.location.replace("/sign-in");return;}const access=await (neonClient as any).rpc("is_platform_admin");if(access.error)throw access.error;if(!access.data){setAllowed(false);return;}setAllowed(true);const [dq,bq]=await Promise.all([(neonClient as any).rpc("admin_dashboard"),(neonClient as any).rpc("admin_list_businesses")]);if(dq.error)throw dq.error;if(bq.error)throw bq.error;setDashboard(dq.data as Dashboard);setBusinesses((Array.isArray(bq.data)?bq.data:[]) as Business[]);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível abrir o Nassus Admin.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function setState(item:Business,plan:Business["plan"],status:string){setError("");const result=await (neonClient as any).rpc("admin_set_business_state",{p_business_id:item.id,p_plan:plan,p_status:status});if(result.error){setError(result.error.message||"Não foi possível atualizar.");return;}await load();}
  async function extend(item:Business){const result=await (neonClient as any).rpc("admin_extend_trial",{p_business_id:item.id,p_days:7});if(result.error){setError(result.error.message||"Não foi possível estender o teste.");return;}await load();}
  async function signOut(){await neonClient.auth.signOut();window.location.replace("/sign-in");}
  if(loading)return <main className="admin-locked"><div className="admin-locked-card"><div className="brand-mark" style={{margin:"0 auto"}}>N</div><h1>Nassus Admin</h1><p>Validando acesso administrativo...</p></div></main>;
  if(allowed===false)return <main className="admin-locked"><div className="admin-locked-card"><div className="brand-mark" style={{margin:"0 auto"}}>N</div><span className="eyebrow">ÁREA RESTRITA</span><h1>Nassus Admin</h1><p>Esta conta não possui permissão de administrador da plataforma. O acesso é controlado diretamente no banco e não pode ser ativado pelo navegador.</p><a className="primary" href="/">Voltar ao sistema</a></div></main>;
  if(!dashboard)return <main className="admin-locked"><div className="admin-locked-card"><h1>Não foi possível abrir</h1><p>{error}</p><button className="primary" onClick={()=>void load()}>Tentar novamente</button></div></main>;
  return <main className="admin-page"><div className="admin-container"><header className="admin-head"><div><span className="eyebrow">NASSUSINFO • CONTROLE DA PLATAFORMA</span><h1>Nassus Admin</h1><p style={{color:"#646970",margin:0}}>Empresas, planos, trials e receita recorrente em uma visão central.</p></div><div style={{display:"flex",gap:8}}><a className="secondary" href="/">Abrir Gestão</a><button className="secondary" onClick={()=>void signOut()}>Sair</button></div></header>{error?<div className="notice error">{error}</div>:null}<section className="admin-stats"><article className="admin-stat"><span>Empresas</span><strong>{dashboard.businesses}</strong></article><article className="admin-stat"><span>Ativas</span><strong>{dashboard.active}</strong></article><article className="admin-stat"><span>Trials</span><strong>{dashboard.trials}</strong></article><article className="admin-stat"><span>Em atraso</span><strong>{dashboard.past_due}</strong></article><article className="admin-stat"><span>Usuários</span><strong>{dashboard.users}</strong></article><article className="admin-stat"><span>MRR estimado</span><strong>{formatMoney(dashboard.mrr)}</strong></article></section><section className="admin-table-card"><div className="panel-head"><div><span className="eyebrow">CLIENTES DO SAAS</span><h2>Empresas cadastradas</h2></div><button className="secondary" onClick={()=>void load()}>Atualizar</button></div>{businesses.length?<div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Plano</th><th>Status</th><th>Clientes</th><th>Usuários</th><th>Trial</th><th className="right">Administração</th></tr></thead><tbody>{businesses.map(item=><tr key={item.id}><td><strong>{item.name}</strong><br/><small>{item.slug}</small></td><td><span className={`badge ${item.plan==="professional"?"blue":""}`}>{item.plan==="professional"?"Profissional":"Essencial"}</span></td><td><span className={`badge ${item.status==="active"?"green":item.status==="past_due"||item.status==="suspended"?"red":"orange"}`}>{item.status}</span></td><td>{item.client_count}</td><td>{item.user_count}</td><td>{item.trial_ends_at?new Date(item.trial_ends_at).toLocaleDateString("pt-BR"):"—"}</td><td><div className="admin-actions"><button className="mini-button" onClick={()=>void extend(item)}>+7 dias</button><button className="mini-button" onClick={()=>void setState(item,"essential","active")}>Essencial</button><button className="mini-button ok" onClick={()=>void setState(item,"professional","active")}>Profissional</button><button className="mini-button cancel" onClick={()=>void setState(item,item.plan,"suspended")}>Suspender</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><strong>Nenhuma empresa ainda</strong><p>As empresas aparecerão aqui após o primeiro onboarding.</p></div>}</section></div></main>;
}
