"use client";

import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/app-shell";
import { neonClient } from "@/lib/neon";
import { formatMoney, friendlyWorkspaceError, requireFinance, requireWorkspace, type Workspace } from "@/lib/workspace";

type Finance={type:"income"|"expense";amount:number|string;paid_at:string|null;category:string|null;description:string;due_date:string|null;created_at:string};type Appointment={status:string;service_id:string|null;starts_at:string};type Service={id:string;name:string};type Quote={status:string;total:number|string;created_at:string};

export default function ReportsPage(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null);const [clientCount,setClientCount]=useState(0);const [memberCount,setMemberCount]=useState(1);const [finance,setFinance]=useState<Finance[]>([]);const [appointments,setAppointments]=useState<Appointment[]>([]);const [services,setServices]=useState<Service[]>([]);const [quotes,setQuotes]=useState<Quote[]>([]);const [period,setPeriod]=useState<"30"|"90"|"all">("30");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let active=true;async function load(){try{const current=await requireWorkspace();if(!current||!active)return;const access=await requireFinance(current);if(!access)return;const [cq,mq,fq,aq,sq,qq]=await Promise.all([neonClient.from("clients").select("id").eq("business_id",current.business.id),neonClient.from("business_members").select("id").eq("business_id",current.business.id).eq("active",true),neonClient.from("financial_entries").select("type,amount,paid_at,category,description,due_date,created_at").eq("business_id",current.business.id).limit(3000),neonClient.from("appointments").select("status,service_id,starts_at").eq("business_id",current.business.id).limit(3000),neonClient.from("services").select("id,name").eq("business_id",current.business.id),neonClient.from("quotes").select("status,total,created_at").eq("business_id",current.business.id).limit(3000)]);if(fq.error)throw fq.error;setWorkspace(current);setClientCount(Array.isArray(cq.data)?cq.data.length:0);setMemberCount(Array.isArray(mq.data)?mq.data.length:1);setFinance((Array.isArray(fq.data)?fq.data:[]) as Finance[]);setAppointments((Array.isArray(aq.data)?aq.data:[]) as Appointment[]);setServices((Array.isArray(sq.data)?sq.data:[]) as Service[]);setQuotes((Array.isArray(qq.data)?qq.data:[]) as Quote[]);}catch(reason){setError(friendlyWorkspaceError(reason));}finally{if(active)setLoading(false);}}void load();return()=>{active=false};},[]);
 const cutoff=useMemo(()=>period==="all"?0:Date.now()-Number(period)*86400000,[period]);const periodFinance=useMemo(()=>finance.filter(item=>!cutoff||new Date(item.created_at).getTime()>=cutoff),[finance,cutoff]);const periodAppointments=useMemo(()=>appointments.filter(item=>!cutoff||new Date(item.starts_at).getTime()>=cutoff),[appointments,cutoff]);const periodQuotes=useMemo(()=>quotes.filter(item=>!cutoff||new Date(item.created_at).getTime()>=cutoff),[quotes,cutoff]);
 const metrics=useMemo(()=>{let revenue=0,expenses=0;for(const item of periodFinance){if(!item.paid_at)continue;if(item.type==="income")revenue+=Number(item.amount||0);else expenses+=Number(item.amount||0);}const completed=periodAppointments.filter(a=>a.status==="completed").length;const approved=periodQuotes.filter(q=>["approved","converted"].includes(q.status));const quoteTotal=approved.reduce((sum,q)=>sum+Number(q.total||0),0);return{revenue,expenses,result:revenue-expenses,completed,quoteTotal,conversion:periodQuotes.length?approved.length/periodQuotes.length*100:0};},[periodFinance,periodAppointments,periodQuotes]);
 const serviceUsage=useMemo(()=>{const counts=new Map<string,number>();for(const appointment of periodAppointments){if(appointment.service_id&&appointment.status!=="cancelled")counts.set(appointment.service_id,(counts.get(appointment.service_id)||0)+1);}return services.map(service=>({name:service.name,count:counts.get(service.id)||0})).sort((a,b)=>b.count-a.count).slice(0,8);},[periodAppointments,services]);const maxService=Math.max(1,...serviceUsage.map(item=>item.count));
 function exportCsv(){if(!workspace)return;const esc=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`;const rows=[["Tipo","Descrição","Categoria","Valor","Vencimento","Pago em","Criado em"],...periodFinance.map(item=>[item.type==="income"?"Receita":"Despesa",item.description,item.category||"",Number(item.amount||0).toFixed(2),item.due_date||"",item.paid_at||"",item.created_at])];const csv="\ufeff"+rows.map(row=>row.map(esc).join(";")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`nassus-relatorio-${workspace.business.slug}.csv`;a.click();URL.revokeObjectURL(url);}
 if(loading)return <main className="loading"><div className="brand-mark">N</div><h1>Relatórios</h1><p>Calculando indicadores...</p></main>;if(!workspace)return <main className="loading"><h1>Não foi possível abrir</h1><p>{error}</p></main>;
 return <AppShell business={workspace.business} user={workspace.user} clientCount={clientCount} memberCount={memberCount}><main className="module-content"><div className="module-head"><div><span className="eyebrow">INTELIGÊNCIA DO NEGÓCIO</span><h1>Relatórios</h1><p>Indicadores financeiros e operacionais calculados em tempo real.</p></div><div className="toolbar"><select value={period} onChange={e=>setPeriod(e.target.value as "30"|"90"|"all")}><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="all">Todo o período</option></select><button className="secondary" onClick={exportCsv}>Exportar CSV</button></div></div>{error?<div className="notice error">{error}</div>:null}<section className="summary-row"><article className="summary-card"><span>Faturamento recebido</span><strong>{formatMoney(metrics.revenue)}</strong><small>Receitas pagas no período</small></article><article className="summary-card"><span>Resultado realizado</span><strong>{formatMoney(metrics.result)}</strong><small>Receitas menos despesas</small></article><article className="summary-card"><span>Atendimentos concluídos</span><strong>{metrics.completed}</strong><small>Agenda finalizada</small></article><article className="summary-card"><span>Conversão de orçamentos</span><strong>{metrics.conversion.toFixed(0)}%</strong><small>{formatMoney(metrics.quoteTotal)} aprovados</small></article></section><div className="grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">DEMANDA</span><h2>Serviços mais agendados</h2></div></div>{serviceUsage.length?<div className="report-bars">{serviceUsage.map(item=><div className="report-row" key={item.name}><strong>{item.name}</strong><div className="bar-track"><i style={{width:`${item.count/maxService*100}%`}}/></div><span className="right">{item.count} agend.</span></div>)}</div>:<div className="empty-state"><strong>Ainda sem dados suficientes</strong><p>Quando a agenda começar a ser utilizada, os serviços mais procurados aparecem aqui.</p></div>}</section><aside className="panel"><div className="panel-head"><div><span className="eyebrow">SAÚDE DA OPERAÇÃO</span><h2>Resumo</h2></div></div><div className="info-list"><div><span>Clientes cadastrados</span><strong>{clientCount}</strong></div><div><span>Usuários ativos</span><strong>{memberCount}</strong></div><div><span>Serviços no catálogo</span><strong>{services.length}</strong></div><div><span>Agendamentos no período</span><strong>{periodAppointments.length}</strong></div><div><span>Orçamentos no período</span><strong>{periodQuotes.length}</strong></div><div><span>Despesas realizadas</span><strong>{formatMoney(metrics.expenses)}</strong></div></div><div className="limit-note"><strong>Exportação incluída</strong><br/>O CSV pode ser aberto no Excel, Google Sheets ou LibreOffice para análises adicionais.</div></aside></div></main></AppShell>;
}
