-- Estrutura documental do Nassus CRM.
-- Não execute automaticamente em produção.

CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id text NOT NULL,
  name varchar NOT NULL,
  company varchar NOT NULL DEFAULT '',
  segment varchar NOT NULL DEFAULT '',
  phone varchar NOT NULL DEFAULT '',
  email varchar NOT NULL DEFAULT '',
  status varchar NOT NULL DEFAULT 'novo',
  estimated_value integer NOT NULL DEFAULT 0,
  next_action varchar NOT NULL DEFAULT '',
  next_action_date date,
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clients_status_check CHECK (
    status IN ('novo', 'contato', 'proposta', 'negociacao', 'fechado', 'perdido')
  ),
  CONSTRAINT clients_estimated_value_check CHECK (estimated_value >= 0)
);

CREATE INDEX IF NOT EXISTS clients_owner_updated_idx
  ON public.clients (owner_id, updated_at DESC);
