-- Estrutura documental do Nassus CRM com Neon Data API e RLS.
-- Não execute automaticamente em produção sem revisar o estado atual.

CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id text NOT NULL DEFAULT (auth.user_id()),
  name varchar NOT NULL,
  company varchar NOT NULL DEFAULT '',
  segment varchar NOT NULL DEFAULT '',
  phone varchar NOT NULL DEFAULT '',
  email varchar NOT NULL DEFAULT '',
  status varchar NOT NULL DEFAULT 'novo',
  estimated_value integer NOT NULL DEFAULT 0,
  next_action varchar NOT NULL DEFAULT '',
  next_action_date date,
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clients_status_check CHECK (
    status IN ('novo', 'contato', 'proposta', 'negociacao', 'fechado', 'perdido')
  ),
  CONSTRAINT clients_estimated_value_check CHECK (estimated_value >= 0)
);

CREATE INDEX IF NOT EXISTS clients_owner_updated_idx
  ON public.clients (owner_id, updated_at DESC);

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.clients TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clients_owner_access ON public.clients;
CREATE POLICY clients_owner_access ON public.clients
  FOR ALL
  TO authenticated
  USING ((SELECT auth.user_id()) = owner_id)
  WITH CHECK ((SELECT auth.user_id()) = owner_id);
