"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { resetPassword } from "@/lib/auth-password";
import { PASSWORD_HINT, PASSWORD_MIN_LENGTH, passwordValidationError } from "@/lib/password";

export default function ResetPasswordPage(){
  const [token,setToken]=useState<string|null>(null);const [message,setMessage]=useState("");const [done,setDone]=useState(false);const [loading,setLoading]=useState(false);
  useEffect(()=>{const url=new URL(window.location.href);const value=url.searchParams.get("token")?.trim()||"";setToken(value);if(url.search)window.history.replaceState(window.history.state,"",url.pathname+url.hash);},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const first=String(data.get("newPassword")||"");const second=String(data.get("confirmation")||"");if(!token)return setMessage("O link é inválido, está incompleto ou expirou.");const validation=passwordValidationError(first);if(validation)return setMessage(validation);if(first!==second)return setMessage("As duas senhas não são iguais.");setLoading(true);setMessage("");try{await resetPassword(token,first);setToken("");setDone(true);}catch(reason){setMessage(reason instanceof Error?reason.message:"Não foi possível concluir a redefinição.");}finally{setLoading(false);}}
  const checking=token===null;const invalid=token===""&&!done;
  return <main className="auth-page"><section className="auth-visual"><div className="auth-brand"><div className="brand-mark">N</div><div><strong>Nassus Gestão</strong><small>NOVA SENHA</small></div></div><div className="auth-copy"><span className="eyebrow">ACESSO PROTEGIDO</span><h1>Crie uma nova senha para sua conta.</h1><p>O link recebido por e-mail é individual e possui validade limitada.</p></div></section><section className="auth-side"><div className="auth-card"><div className="auth-card-mark">NG</div><span className="eyebrow">REDEFINIÇÃO</span><h2>Nova senha</h2><p>Use uma senha forte e diferente das anteriores.</p>{checking?<p className="muted">Validando link...</p>:null}{invalid?<p className="auth-error" role="alert">O link é inválido, está incompleto ou expirou.</p>:null}{!checking&&!invalid&&!done?<form onSubmit={submit}><label>Nova senha<input name="newPassword" type="password" minLength={PASSWORD_MIN_LENGTH} required autoComplete="new-password"/></label><label>Confirmar nova senha<input name="confirmation" type="password" minLength={PASSWORD_MIN_LENGTH} required autoComplete="new-password"/></label><p className="muted small">{PASSWORD_HINT}</p>{message?<p className="auth-error" role="alert">{message}</p>:null}<button className="primary auth-submit" disabled={loading}>{loading?"Atualizando...":"Salvar nova senha"}</button></form>:null}{done?<div className="notice success">Senha redefinida com sucesso. Entre novamente com a nova senha.</div>:null}<p className="auth-switch"><Link href={done?"/sign-in":"/forgot-password"}>{done?"Ir para o login →":"← Solicitar outro link"}</Link></p></div></section></main>;
}
