-- Nassus CRM Evolution V2 — 2026-08-08
-- Itens: lixeira, segurança, LGPD, retenção, auditoria, permissões, cofre, backup, saúde e performance.
-- Idempotente onde possível. Aplicar somente após backup verificado e testes em branch Neon.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- AUDITORIA CENTRAL
CREATE TABLE IF NOT EXISTS public.crm_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_owner_id uuid NOT NULL,
  actor_user_id uuid,
  event_type text NOT NULL,
  entity_type text NOT NULL DEFAULT '',
  entity_id text NOT NULL DEFAULT '',
  severity text NOT NULL DEFAULT 'info',
  outcome text NOT NULL DEFAULT 'success',
  message text NOT NULL DEFAULT '',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS crm_audit_events_workspace_created_idx ON public.crm_audit_events(workspace_owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS crm_audit_events_event_created_idx ON public.crm_audit_events(workspace_owner_id, event_type, created_at DESC);
REVOKE ALL ON public.crm_audit_events FROM PUBLIC, anonymous, authenticated;

CREATE OR REPLACE FUNCTION public.crm_record_audit_event(
  p_event_type text, p_entity_type text DEFAULT '', p_entity_id text DEFAULT '',
  p_severity text DEFAULT 'info', p_outcome text DEFAULT 'success',
  p_message text DEFAULT '', p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_id bigint; v_owner uuid:=public.crm_workspace_owner_id();
BEGIN
  IF v_owner IS NULL OR public.crm_auth_user_id() IS NULL THEN RAISE EXCEPTION 'Sessão inválida.'; END IF;
  INSERT INTO public.crm_audit_events(workspace_owner_id,actor_user_id,event_type,entity_type,entity_id,severity,outcome,message,metadata)
  VALUES(v_owner,public.crm_auth_user_id(),left(coalesce(p_event_type,''),80),left(coalesce(p_entity_type,''),60),left(coalesce(p_entity_id,''),120),
    CASE WHEN p_severity IN ('info','warning','error','critical') THEN p_severity ELSE 'info' END,
    CASE WHEN p_outcome IN ('success','denied','failed') THEN p_outcome ELSE 'success' END,
    left(coalesce(p_message,''),500),coalesce(p_metadata,'{}'::jsonb)-ARRAY['password','token','access_code','cpf','cnpj','document','secret'])
  RETURNING id INTO v_id;
  RETURN v_id;
END $function$;
REVOKE ALL ON FUNCTION public.crm_record_audit_event(text,text,text,text,text,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_record_audit_event(text,text,text,text,text,text,jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_list_audit_events(p_limit integer DEFAULT 200)
RETURNS TABLE(id bigint,event_type text,entity_type text,entity_id text,severity text,outcome text,message text,metadata jsonb,actor_name text,created_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT e.id,e.event_type,e.entity_type,e.entity_id,e.severity,e.outcome,e.message,e.metadata,
       coalesce(m.name,m.email,'Sistema'),e.created_at
FROM public.crm_audit_events e
LEFT JOIN public.crm_team_members m ON m.user_id=e.actor_user_id AND m.workspace_owner_id=e.workspace_owner_id
WHERE e.workspace_owner_id=public.crm_workspace_owner_id() AND public.crm_can('admin.view')
ORDER BY e.created_at DESC LIMIT greatest(1,least(coalesce(p_limit,200),500)) $function$;
REVOKE ALL ON FUNCTION public.crm_list_audit_events(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_list_audit_events(integer) TO authenticated;

-- RETENÇÃO POR TIPO DE DADO
CREATE TABLE IF NOT EXISTS public.crm_retention_policies (
  workspace_owner_id uuid NOT NULL,
  record_type text NOT NULL,
  retention_days integer NOT NULL CHECK (retention_days BETWEEN 1 AND 3650),
  preserve_signed boolean NOT NULL DEFAULT false,
  legal_basis text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(workspace_owner_id,record_type)
);
REVOKE ALL ON public.crm_retention_policies FROM PUBLIC, anonymous, authenticated;
INSERT INTO public.crm_retention_policies(workspace_owner_id,record_type,retention_days,preserve_signed,legal_basis)
SELECT workspace_owner_id,x.record_type,x.days,x.preserve,x.basis
FROM public.crm_settings CROSS JOIN (VALUES
 ('clients',90,false,'Gestão comercial e direitos do titular'),
 ('projects',90,false,'Execução de serviços'),
 ('payments',365,true,'Comprovação financeira e exercício regular de direitos'),
 ('commercial_documents',365,true,'Execução contratual e exercício regular de direitos'),
 ('tasks',30,false,'Operação interna'),('site_audits',90,false,'Prestação de serviço'),
 ('site_infrastructure',90,false,'Operação técnica'),('access_credentials',30,false,'Segurança e minimização'),
 ('renewal_costs',365,false,'Gestão financeira')) AS x(record_type,days,preserve,basis)
ON CONFLICT(workspace_owner_id,record_type) DO NOTHING;

CREATE OR REPLACE FUNCTION public.crm_list_retention_policies()
RETURNS TABLE(record_type text,retention_days integer,preserve_signed boolean,legal_basis text,updated_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT p.record_type,p.retention_days,p.preserve_signed,p.legal_basis,p.updated_at
FROM public.crm_retention_policies p WHERE p.workspace_owner_id=public.crm_workspace_owner_id() AND public.crm_can('admin.view') ORDER BY p.record_type $function$;
REVOKE ALL ON FUNCTION public.crm_list_retention_policies() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_list_retention_policies() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_update_retention_policy(p_record_type text,p_days integer,p_preserve_signed boolean,p_legal_basis text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Sem permissão para alterar retenção.'; END IF;
 IF p_days<1 OR p_days>3650 THEN RAISE EXCEPTION 'Prazo de retenção inválido.'; END IF;
 INSERT INTO public.crm_retention_policies(workspace_owner_id,record_type,retention_days,preserve_signed,legal_basis,updated_at)
 VALUES(public.crm_workspace_owner_id(),left(p_record_type,80),p_days,p_preserve_signed,left(coalesce(p_legal_basis,''),500),now())
 ON CONFLICT(workspace_owner_id,record_type) DO UPDATE SET retention_days=excluded.retention_days,preserve_signed=excluded.preserve_signed,legal_basis=excluded.legal_basis,updated_at=now();
 PERFORM public.crm_record_audit_event('retention_policy_updated','retention_policy',p_record_type,'warning','success','Política de retenção atualizada',jsonb_build_object('days',p_days,'preserveSigned',p_preserve_signed));
 RETURN true;
END $function$;
REVOKE ALL ON FUNCTION public.crm_update_retention_policy(text,integer,boolean,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_update_retention_policy(text,integer,boolean,text) TO authenticated;

-- LIXEIRA V2
CREATE INDEX IF NOT EXISTS commercial_documents_deleted_batch_idx ON public.commercial_documents(deleted_batch) WHERE deleted_at IS NOT NULL;
CREATE OR REPLACE FUNCTION public.crm_list_trash_v2()
RETURNS TABLE(batch_id uuid,table_name text,record_id bigint,record_type text,label text,deleted_at timestamptz,deleted_reason text,purge_at timestamptz,deleted_by uuid,deleted_by_name text,protected_evidence boolean)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
WITH items(batch_id,table_name,record_id,record_type,label,deleted_at,deleted_reason,deleted_by,protected_evidence,retention_type) AS (
 SELECT deleted_batch,'clients',id,'Cliente',coalesce(nullif(trade_name,''),nullif(company,''),name),deleted_at,deleted_reason,deleted_by,false,'clients' FROM public.clients WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'projects',id,'Projeto',name,deleted_at,deleted_reason,deleted_by,false,'projects' FROM public.projects WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'payments',id,'Cobrança',description,deleted_at,deleted_reason,deleted_by,false,'payments' FROM public.payments WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT d.deleted_batch,'commercial_documents',d.id,CASE d.document_type WHEN 'contrato' THEN 'Contrato' WHEN 'recibo' THEN 'Comprovante' ELSE 'Proposta' END,d.number||' · '||d.title,d.deleted_at,d.deleted_reason,d.deleted_by,(d.signature_status='signed' OR d.signed_at IS NOT NULL OR EXISTS(SELECT 1 FROM public.document_signatures s WHERE s.document_id=d.id)),'commercial_documents' FROM public.commercial_documents d WHERE d.owner_id=public.crm_workspace_owner_id()::text AND d.deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'tasks',id,'Tarefa',title,deleted_at,deleted_reason,deleted_by,false,'tasks' FROM public.tasks WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'site_infrastructure',id,'Infraestrutura',coalesce(nullif(site_name,''),nullif(primary_domain,''),'Site'),deleted_at,deleted_reason,deleted_by,false,'site_infrastructure' FROM public.site_infrastructure WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'access_credentials',id,'Acesso',coalesce(nullif(platform,''),nullif(category,''),'Credencial'),deleted_at,deleted_reason,deleted_by,false,'access_credentials' FROM public.access_credentials WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'renewal_costs',id,'Renovação',coalesce(nullif(plan_domain,''),nullif(provider,''),nullif(item_type,''),'Custo'),deleted_at,deleted_reason,deleted_by,false,'renewal_costs' FROM public.renewal_costs WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
 UNION ALL SELECT deleted_batch,'site_audits',id,'Auditoria',coalesce(nullif(title,''),url),deleted_at,deleted_reason,deleted_by,false,'site_audits' FROM public.site_audits WHERE owner_id=public.crm_workspace_owner_id()::text AND deleted_at IS NOT NULL
)
SELECT i.batch_id,i.table_name,i.record_id,i.record_type,i.label,i.deleted_at,i.deleted_reason,
       i.deleted_at+make_interval(days=>coalesce(p.retention_days,s.trash_retention_days,30)),i.deleted_by,
       coalesce(tm.name,tm.email,'Usuário do CRM'),i.protected_evidence
FROM items i
LEFT JOIN public.crm_retention_policies p ON p.workspace_owner_id=public.crm_workspace_owner_id() AND p.record_type=i.retention_type
LEFT JOIN public.crm_settings s ON s.workspace_owner_id=public.crm_workspace_owner_id()
LEFT JOIN public.crm_team_members tm ON tm.user_id=i.deleted_by AND tm.workspace_owner_id=public.crm_workspace_owner_id()
WHERE public.crm_can('admin.view') ORDER BY i.deleted_at DESC,i.batch_id,i.table_name $function$;
REVOKE ALL ON FUNCTION public.crm_list_trash_v2() FROM PUBLIC, anonymous;
GRANT EXECUTE ON FUNCTION public.crm_list_trash_v2() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_purge_expired_trash() RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_batch uuid; v_total integer:=0;
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RETURN 0; END IF;
 FOR v_batch IN SELECT DISTINCT t.batch_id FROM public.crm_list_trash_v2() t WHERE t.batch_id IS NOT NULL AND t.purge_at<=now() AND NOT t.protected_evidence
 LOOP v_total:=v_total+public.crm_purge_trash_batch(v_batch); END LOOP;
 RETURN v_total;
END $function$;

-- LGPD / TITULARES
CREATE TABLE IF NOT EXISTS public.crm_data_subject_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_owner_id uuid NOT NULL,client_id bigint,
 request_type text NOT NULL,status text NOT NULL DEFAULT 'open',notes text NOT NULL DEFAULT '',requested_by uuid,
 requested_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz
);
CREATE INDEX IF NOT EXISTS crm_data_subject_requests_workspace_idx ON public.crm_data_subject_requests(workspace_owner_id,requested_at DESC);
CREATE INDEX IF NOT EXISTS crm_data_subject_requests_client_idx ON public.crm_data_subject_requests(workspace_owner_id,client_id,requested_at DESC) WHERE client_id IS NOT NULL;
REVOKE ALL ON public.crm_data_subject_requests FROM PUBLIC, anonymous, authenticated;

CREATE OR REPLACE FUNCTION public.crm_create_data_subject_request(p_client_id bigint,p_request_type text,p_notes text DEFAULT '') RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_id bigint;
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Sem permissão para registrar solicitações LGPD.'; END IF;
 IF p_request_type NOT IN ('access','correction','portability','anonymization','deletion','information') THEN RAISE EXCEPTION 'Tipo de solicitação inválido.'; END IF;
 INSERT INTO public.crm_data_subject_requests(workspace_owner_id,client_id,request_type,notes,requested_by)
 VALUES(public.crm_workspace_owner_id(),p_client_id,p_request_type,left(coalesce(p_notes,''),1000),public.crm_auth_user_id()) RETURNING id INTO v_id;
 PERFORM public.crm_record_audit_event('lgpd_request_created','client',p_client_id::text,'info','success','Solicitação de titular registrada',jsonb_build_object('requestId',v_id,'type',p_request_type));
 RETURN v_id;
END $function$;
REVOKE ALL ON FUNCTION public.crm_create_data_subject_request(bigint,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_create_data_subject_request(bigint,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_list_data_subject_requests()
RETURNS TABLE(id bigint,client_id bigint,client_name text,request_type text,status text,notes text,requested_at timestamptz,completed_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT r.id,r.client_id,coalesce(nullif(c.trade_name,''),nullif(c.company,''),c.name,'Titular removido'),r.request_type,r.status,r.notes,r.requested_at,r.completed_at
FROM public.crm_data_subject_requests r LEFT JOIN public.clients c ON c.id=r.client_id AND c.owner_id=r.workspace_owner_id::text
WHERE r.workspace_owner_id=public.crm_workspace_owner_id() AND public.crm_can('admin.view') ORDER BY r.requested_at DESC $function$;
REVOKE ALL ON FUNCTION public.crm_list_data_subject_requests() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_list_data_subject_requests() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_complete_data_subject_request(p_id bigint,p_notes text DEFAULT '') RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Sem permissão.'; END IF;
 UPDATE public.crm_data_subject_requests SET status='completed',notes=CASE WHEN coalesce(p_notes,'')='' THEN notes ELSE left(p_notes,1000) END,completed_at=now()
 WHERE id=p_id AND workspace_owner_id=public.crm_workspace_owner_id();
 IF NOT FOUND THEN RAISE EXCEPTION 'Solicitação não encontrada.'; END IF;
 PERFORM public.crm_record_audit_event('lgpd_request_completed','lgpd_request',p_id::text,'info','success','Solicitação LGPD concluída','{}'::jsonb);
 RETURN true;
END $function$;
REVOKE ALL ON FUNCTION public.crm_complete_data_subject_request(bigint,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_complete_data_subject_request(bigint,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_data_subject_inventory(p_query text DEFAULT '')
RETURNS TABLE(client_id bigint,display_name text,masked_document text,email_hint text,status text,projects_count bigint,payments_count bigint,documents_count bigint,signed_documents_count bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT c.id,coalesce(nullif(c.trade_name,''),nullif(c.company,''),c.name),
 CASE WHEN length(regexp_replace(coalesce(c.document,''),'\D','','g'))>4 THEN repeat('*',greatest(length(regexp_replace(coalesce(c.document,''),'\D','','g'))-4,0))||right(regexp_replace(coalesce(c.document,''),'\D','','g'),4) ELSE coalesce(c.document,'') END,
 CASE WHEN position('@' in coalesce(c.email,''))>1 THEN left(c.email,1)||'***@'||split_part(c.email,'@',2) ELSE '' END,
 CASE WHEN c.deleted_at IS NULL THEN 'active' ELSE 'trash' END,
 (SELECT count(*) FROM public.projects p WHERE p.client_id=c.id AND p.owner_id=c.owner_id),
 (SELECT count(*) FROM public.payments p WHERE p.client_id=c.id AND p.owner_id=c.owner_id),
 (SELECT count(*) FROM public.commercial_documents d WHERE d.client_id=c.id AND d.owner_id=c.owner_id),
 (SELECT count(*) FROM public.commercial_documents d WHERE d.client_id=c.id AND d.owner_id=c.owner_id AND (d.signature_status='signed' OR d.signed_at IS NOT NULL OR EXISTS(SELECT 1 FROM public.document_signatures s WHERE s.document_id=d.id)))
FROM public.clients c
WHERE c.owner_id=public.crm_workspace_owner_id()::text AND public.crm_can('admin.view')
AND (coalesce(trim(p_query),'')='' OR lower(coalesce(c.name,'')||' '||coalesce(c.trade_name,'')||' '||coalesce(c.company,'')||' '||coalesce(c.email,'')||' '||coalesce(c.document,'')) LIKE '%'||lower(trim(p_query))||'%')
ORDER BY c.updated_at DESC LIMIT 100 $function$;
REVOKE ALL ON FUNCTION public.crm_data_subject_inventory(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_data_subject_inventory(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_export_data_subject(p_client_id bigint) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_owner text:=public.crm_workspace_owner_id()::text; v_result jsonb;
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Sem permissão para exportar dados do titular.'; END IF;
 SELECT jsonb_build_object('generatedAt',now(),
  'client',(SELECT to_jsonb(c)-'deleted_by'-'deleted_batch' FROM public.clients c WHERE c.id=p_client_id AND c.owner_id=v_owner),
  'projects',coalesce((SELECT jsonb_agg(to_jsonb(p)-'deleted_by'-'deleted_batch') FROM public.projects p WHERE p.client_id=p_client_id AND p.owner_id=v_owner),'[]'::jsonb),
  'payments',coalesce((SELECT jsonb_agg(to_jsonb(p)-'deleted_by'-'deleted_batch') FROM public.payments p WHERE p.client_id=p_client_id AND p.owner_id=v_owner),'[]'::jsonb),
  'documents',coalesce((SELECT jsonb_agg(jsonb_build_object('id',d.id,'number',d.number,'type',d.document_type,'title',d.title,'status',d.status,'issueDate',d.issue_date,'amount',d.amount,'signatureStatus',d.signature_status,'signedAt',d.signed_at,'hash',d.document_hash)) FROM public.commercial_documents d WHERE d.client_id=p_client_id AND d.owner_id=v_owner),'[]'::jsonb)) INTO v_result;
 IF v_result->'client' IS NULL THEN RAISE EXCEPTION 'Titular não encontrado.'; END IF;
 RETURN v_result;
END $function$;
REVOKE ALL ON FUNCTION public.crm_export_data_subject(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_export_data_subject(bigint) TO authenticated;

-- PERFIS E PERMISSÕES
CREATE TABLE IF NOT EXISTS public.crm_role_presets(role text PRIMARY KEY,label text NOT NULL,description text NOT NULL,permissions jsonb NOT NULL DEFAULT '{}'::jsonb,updated_at timestamptz NOT NULL DEFAULT now());
REVOKE ALL ON public.crm_role_presets FROM PUBLIC, anonymous, authenticated;
INSERT INTO public.crm_role_presets(role,label,description,permissions) VALUES
 ('owner','Proprietário','Controle total do workspace','{"*":true}'::jsonb),
 ('admin','Administrador','Administração, segurança e operação completa','{"*":true}'::jsonb),
 ('commercial','Comercial','Clientes, propostas, contratos e visão de relatórios','{"clients.view":true,"clients.write":true,"projects.view":true,"documents.view":true,"documents.write":true,"reports.view":true}'::jsonb),
 ('operations','Operações','Projetos, agenda e infraestrutura sem financeiro administrativo','{"clients.view":true,"projects.view":true,"projects.write":true,"tasks.view":true,"tasks.write":true,"infrastructure.view":true,"infrastructure.write":true,"documents.view":true}'::jsonb),
 ('finance','Financeiro','Cobranças, parcelas e visão de clientes/projetos','{"clients.view":true,"projects.view":true,"finance.view":true,"finance.write":true,"documents.view":true,"reports.view":true}'::jsonb),
 ('viewer','Somente leitura','Consulta sem alterações','{"clients.view":true,"projects.view":true,"finance.view":true,"documents.view":true,"tasks.view":true,"infrastructure.view":true,"reports.view":true}'::jsonb)
ON CONFLICT(role) DO UPDATE SET label=excluded.label,description=excluded.description,permissions=excluded.permissions,updated_at=now();

CREATE OR REPLACE FUNCTION public.crm_list_role_presets() RETURNS TABLE(role text,label text,description text,permissions jsonb)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT p.role,p.label,p.description,p.permissions FROM public.crm_role_presets p WHERE public.crm_can('admin.view')
ORDER BY CASE p.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'commercial' THEN 2 WHEN 'operations' THEN 3 WHEN 'finance' THEN 4 ELSE 5 END $function$;
REVOKE ALL ON FUNCTION public.crm_list_role_presets() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_list_role_presets() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_team_security_overview()
RETURNS TABLE(id bigint,name text,email text,role text,status text,permissions jsonb,joined_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT m.id,m.name,m.email,m.role,m.status,m.permissions,m.joined_at FROM public.crm_team_members m
WHERE m.workspace_owner_id=public.crm_workspace_owner_id() AND public.crm_can('admin.view')
ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,m.name $function$;
REVOKE ALL ON FUNCTION public.crm_team_security_overview() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_team_security_overview() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_apply_role_preset(p_member_id bigint,p_role text) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_permissions jsonb; v_current_role text;
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Sem permissão.'; END IF;
 SELECT role INTO v_current_role FROM public.crm_team_members WHERE id=p_member_id AND workspace_owner_id=public.crm_workspace_owner_id();
 IF v_current_role IS NULL THEN RAISE EXCEPTION 'Membro não encontrado.'; END IF;
 IF v_current_role='owner' THEN RAISE EXCEPTION 'O papel do proprietário não pode ser alterado por preset.'; END IF;
 IF p_role NOT IN ('admin','commercial','operations','finance','viewer') THEN RAISE EXCEPTION 'Perfil inválido.'; END IF;
 SELECT permissions INTO v_permissions FROM public.crm_role_presets WHERE role=p_role;
 UPDATE public.crm_team_members SET role=p_role,permissions=coalesce(v_permissions,'{}'::jsonb),updated_at=now() WHERE id=p_member_id AND workspace_owner_id=public.crm_workspace_owner_id();
 PERFORM public.crm_record_audit_event('team_role_updated','team_member',p_member_id::text,'warning','success','Perfil de acesso atualizado',jsonb_build_object('role',p_role));
 RETURN true;
END $function$;
REVOKE ALL ON FUNCTION public.crm_apply_role_preset(bigint,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_apply_role_preset(bigint,text) TO authenticated;

-- COFRE CRIPTOGRAFADO
CREATE TABLE IF NOT EXISTS public.crm_vault_master(workspace_owner_id uuid PRIMARY KEY,key_material text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),rotated_at timestamptz);
CREATE TABLE IF NOT EXISTS public.crm_vault_items(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_owner_id uuid NOT NULL,client_id bigint,project_id bigint,label text NOT NULL,username_hint text NOT NULL DEFAULT '',secret_cipher bytea NOT NULL,notes text NOT NULL DEFAULT '',created_by uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),last_revealed_at timestamptz);
CREATE INDEX IF NOT EXISTS crm_vault_items_workspace_idx ON public.crm_vault_items(workspace_owner_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS crm_vault_items_client_idx ON public.crm_vault_items(workspace_owner_id,client_id,updated_at DESC) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS crm_vault_items_project_idx ON public.crm_vault_items(workspace_owner_id,project_id,updated_at DESC) WHERE project_id IS NOT NULL;
REVOKE ALL ON public.crm_vault_master FROM PUBLIC, anonymous, authenticated;
REVOKE ALL ON public.crm_vault_items FROM PUBLIC, anonymous, authenticated;
INSERT INTO public.crm_vault_master(workspace_owner_id,key_material) SELECT workspace_owner_id,encode(gen_random_bytes(32),'hex') FROM public.crm_settings ON CONFLICT(workspace_owner_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.crm_vault_put(p_id bigint,p_client_id bigint,p_project_id bigint,p_label text,p_username_hint text,p_secret text,p_notes text DEFAULT '') RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_owner uuid:=public.crm_workspace_owner_id(); v_key text; v_id bigint;
BEGIN
 IF NOT (public.crm_can('infrastructure.write') OR public.crm_can('admin.manage')) THEN RAISE EXCEPTION 'Sem permissão para usar o cofre.'; END IF;
 IF length(coalesce(p_secret,''))<1 OR length(p_secret)>4096 THEN RAISE EXCEPTION 'Segredo inválido.'; END IF;
 INSERT INTO public.crm_vault_master(workspace_owner_id,key_material) VALUES(v_owner,encode(gen_random_bytes(32),'hex')) ON CONFLICT(workspace_owner_id) DO NOTHING;
 SELECT key_material INTO v_key FROM public.crm_vault_master WHERE workspace_owner_id=v_owner;
 IF p_id IS NULL THEN
  INSERT INTO public.crm_vault_items(workspace_owner_id,client_id,project_id,label,username_hint,secret_cipher,notes,created_by)
  VALUES(v_owner,p_client_id,p_project_id,left(trim(p_label),120),left(coalesce(p_username_hint,''),200),pgp_sym_encrypt(p_secret,v_key,'cipher-algo=aes256'),left(coalesce(p_notes,''),1000),public.crm_auth_user_id()) RETURNING id INTO v_id;
 ELSE
  UPDATE public.crm_vault_items SET client_id=p_client_id,project_id=p_project_id,label=left(trim(p_label),120),username_hint=left(coalesce(p_username_hint,''),200),secret_cipher=pgp_sym_encrypt(p_secret,v_key,'cipher-algo=aes256'),notes=left(coalesce(p_notes,''),1000),updated_at=now()
  WHERE id=p_id AND workspace_owner_id=v_owner RETURNING id INTO v_id;
 END IF;
 IF v_id IS NULL THEN RAISE EXCEPTION 'Item do cofre não encontrado.'; END IF;
 PERFORM public.crm_record_audit_event('vault_item_saved','vault_item',v_id::text,'warning','success','Item protegido salvo no cofre',jsonb_build_object('label',left(trim(p_label),120)));
 RETURN v_id;
END $function$;
REVOKE ALL ON FUNCTION public.crm_vault_put(bigint,bigint,bigint,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_vault_put(bigint,bigint,bigint,text,text,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_vault_list() RETURNS TABLE(id bigint,client_id bigint,project_id bigint,label text,username_hint text,notes text,created_at timestamptz,updated_at timestamptz,last_revealed_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT v.id,v.client_id,v.project_id,v.label,v.username_hint,v.notes,v.created_at,v.updated_at,v.last_revealed_at FROM public.crm_vault_items v
WHERE v.workspace_owner_id=public.crm_workspace_owner_id() AND (public.crm_can('infrastructure.view') OR public.crm_can('admin.view')) ORDER BY v.updated_at DESC $function$;
REVOKE ALL ON FUNCTION public.crm_vault_list() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_vault_list() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_vault_reveal(p_id bigint) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_owner uuid:=public.crm_workspace_owner_id(); v_key text; v_secret text;
BEGIN
 IF NOT (public.crm_can('infrastructure.write') OR public.crm_can('admin.manage')) THEN RAISE EXCEPTION 'Sem permissão para revelar segredos.'; END IF;
 SELECT key_material INTO v_key FROM public.crm_vault_master WHERE workspace_owner_id=v_owner;
 SELECT pgp_sym_decrypt(v.secret_cipher,v_key) INTO v_secret FROM public.crm_vault_items v WHERE v.id=p_id AND v.workspace_owner_id=v_owner;
 IF v_secret IS NULL THEN RAISE EXCEPTION 'Item do cofre não encontrado.'; END IF;
 UPDATE public.crm_vault_items SET last_revealed_at=now() WHERE id=p_id AND workspace_owner_id=v_owner;
 PERFORM public.crm_record_audit_event('vault_item_revealed','vault_item',p_id::text,'warning','success','Segredo do cofre revelado por usuário autorizado','{}'::jsonb);
 RETURN v_secret;
END $function$;
REVOKE ALL ON FUNCTION public.crm_vault_reveal(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_vault_reveal(bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_vault_delete(p_id bigint) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Somente administração pode apagar itens do cofre.'; END IF;
 DELETE FROM public.crm_vault_items WHERE id=p_id AND workspace_owner_id=public.crm_workspace_owner_id();
 IF NOT FOUND THEN RAISE EXCEPTION 'Item não encontrado.'; END IF;
 PERFORM public.crm_record_audit_event('vault_item_deleted','vault_item',p_id::text,'warning','success','Item removido do cofre','{}'::jsonb);
 RETURN true;
END $function$;
REVOKE ALL ON FUNCTION public.crm_vault_delete(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_vault_delete(bigint) TO authenticated;

-- BACKUPS VERIFICADOS
CREATE TABLE IF NOT EXISTS public.crm_backup_registry(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_owner_id uuid NOT NULL,backup_label text NOT NULL,provider_ref text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'created',created_at timestamptz NOT NULL DEFAULT now(),verified_at timestamptz,verification_summary jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS crm_backup_registry_workspace_idx ON public.crm_backup_registry(workspace_owner_id,created_at DESC);
REVOKE ALL ON public.crm_backup_registry FROM PUBLIC, anonymous, authenticated;
CREATE OR REPLACE FUNCTION public.crm_register_backup(p_label text,p_provider_ref text,p_status text DEFAULT 'created',p_summary jsonb DEFAULT '{}'::jsonb) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_id bigint;
BEGIN
 IF NOT public.crm_can('admin.manage') THEN RAISE EXCEPTION 'Sem permissão.'; END IF;
 INSERT INTO public.crm_backup_registry(workspace_owner_id,backup_label,provider_ref,status,verified_at,verification_summary)
 VALUES(public.crm_workspace_owner_id(),left(p_label,160),left(coalesce(p_provider_ref,''),200),CASE WHEN p_status IN ('created','verified','failed') THEN p_status ELSE 'created' END,CASE WHEN p_status='verified' THEN now() ELSE NULL END,coalesce(p_summary,'{}'::jsonb)) RETURNING id INTO v_id;
 PERFORM public.crm_record_audit_event('backup_registered','backup',v_id::text,'info','success','Backup registrado',jsonb_build_object('label',left(p_label,160),'status',p_status));
 RETURN v_id;
END $function$;
REVOKE ALL ON FUNCTION public.crm_register_backup(text,text,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_register_backup(text,text,text,jsonb) TO authenticated;
CREATE OR REPLACE FUNCTION public.crm_list_backups() RETURNS TABLE(id bigint,backup_label text,provider_ref text,status text,created_at timestamptz,verified_at timestamptz,verification_summary jsonb)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
SELECT b.id,b.backup_label,b.provider_ref,b.status,b.created_at,b.verified_at,b.verification_summary FROM public.crm_backup_registry b
WHERE b.workspace_owner_id=public.crm_workspace_owner_id() AND public.crm_can('admin.view') ORDER BY b.created_at DESC LIMIT 50 $function$;
REVOKE ALL ON FUNCTION public.crm_list_backups() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_list_backups() TO authenticated;

-- SAÚDE / SESSÃO
CREATE OR REPLACE FUNCTION public.crm_health_snapshot() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public','auth','pg_temp' AS $function$
DECLARE v_owner uuid:=public.crm_workspace_owner_id(); v_result jsonb;
BEGIN
 IF NOT public.crm_can('admin.view') THEN RAISE EXCEPTION 'Sem permissão.'; END IF;
 SELECT jsonb_build_object('database','ok','workspace',CASE WHEN v_owner IS NULL THEN 'unavailable' ELSE 'ok' END,'authUser',CASE WHEN public.crm_auth_user_id() IS NULL THEN 'unavailable' ELSE 'ok' END,
 'clients',(SELECT count(*) FROM public.clients WHERE owner_id=v_owner::text AND deleted_at IS NULL),'projects',(SELECT count(*) FROM public.projects WHERE owner_id=v_owner::text AND deleted_at IS NULL),'payments',(SELECT count(*) FROM public.payments WHERE owner_id=v_owner::text AND deleted_at IS NULL),'documents',(SELECT count(*) FROM public.commercial_documents WHERE owner_id=v_owner::text AND deleted_at IS NULL),
 'pendingSignatures',(SELECT count(*) FROM public.document_signing_links WHERE owner_id=v_owner::text AND status IN ('active','opened') AND expires_at>now()),'trash',(SELECT count(*) FROM public.crm_list_trash_v2()),'auditEvents24h',(SELECT count(*) FROM public.crm_audit_events WHERE workspace_owner_id=v_owner AND created_at>now()-interval '24 hours'),'generatedAt',now()) INTO v_result;
 RETURN v_result;
END $function$;
REVOKE ALL ON FUNCTION public.crm_health_snapshot() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_health_snapshot() TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_auth_security_summary() RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public','auth','neon_auth','pg_temp' AS $function$
DECLARE v_user uuid:=public.crm_auth_user_id();
BEGIN
 IF v_user IS NULL THEN RAISE EXCEPTION 'Sessão inválida.'; END IF;
 RETURN jsonb_build_object('emailVerified',coalesce((SELECT u."emailVerified" FROM neon_auth."user" u WHERE u.id=v_user),false),'activeSessions',(SELECT count(*) FROM neon_auth.session s WHERE s."userId"=v_user AND s."expiresAt">now()),'lastSessionAt',(SELECT max(s."createdAt") FROM neon_auth.session s WHERE s."userId"=v_user),'passwordAccount',EXISTS(SELECT 1 FROM neon_auth.account a WHERE a."userId"=v_user AND a."providerId"='credential'),'generatedAt',now());
END $function$;
REVOKE ALL ON FUNCTION public.crm_auth_security_summary() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crm_auth_security_summary() TO authenticated;

-- ÍNDICES DE VÍNCULO / PERFORMANCE
CREATE INDEX IF NOT EXISTS commercial_documents_project_idx ON public.commercial_documents(project_id,updated_at DESC) WHERE project_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS commercial_documents_payment_idx ON public.commercial_documents(payment_id,updated_at DESC) WHERE payment_id IS NOT NULL;
