"use client";

import { useEffect, useState } from "react";
import AppShell from "@/components/app-shell";
import { neonClient } from "@/lib/neon";
import { friendlyWorkspaceError, requireManager, requireWorkspace, type Workspace } from "@/lib/workspace";

type Day={enabled:boolean;start:string;end:string};type Hours=Record<string,Day>;
const DAYS=[{key:"mon",label:"Segunda-feira"},{key:"tue",label:"Terça-feira"},{key:"wed",label:"Quarta-feira"},{key:"thu",label:"Quinta-feira"},{key:"fri",label:"Sexta-feira"},{key:"sat",label:"Sábado"},{key:"sun",label:"Domingo"}];
const DEFAULT:Hours={mon:{enabled:true,start:"08:00",end:"18:00"},tue:{enabled:true,start:"08:00",end:"18:00"},wed:{enabled:true,start:"08:00",end:"18:00"},thu:{enabled:true,start:"08:00",end:"18:00"},fri:{enabled:true,start:"08:00",end:"18:00"},sat:{enabled:false,start:"08:00",end:"13:00"},sun:{enabled:false,start:"08:00",end:"13:00"}};

export default function BusinessHoursPage(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null);const [hours,setHours]=useState<Hours>(DEFAULT);const [clientCount,setClientCount]=useState(0);const [memberCount,setMemberCount]=useState(1);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
 useEffect(()=>{let active=true;async function load(){try{const current=await requireWorkspace();if(!current||!active)return;const role=await requireManager(current);if(!role)return;const [cq,mq]=await Promise.all([neonClient.from("clients").select("id").eq("business_id",current.business.id),neonClient.from("business_members").select("id").eq("business_id",current.business.id).eq("active",true)]);setWorkspace(current);setClientCount(Array.isArray(cq.data)?cq.data.length:0);setMemberCount(Array.isArray(mq.data)?mq.data.length:1);const stored=current.business.opening_hours as Record<string,Day>|null|undefined;if(stored&&Object.keys(stored).length)setHours({...DEFAULT,...stored});}catch(reason){setError(friendlyWorkspaceError(reason));}finally{if(active)setLoading(false);}}void load();return()=>{active=false};},[]);
 function patch(key:string,patch:Partial<Day>){setHours(prev=>({...prev,[key]:{...prev[key],...patch}}));}
 async function save(){if(!workspace)return;setSaving(true);setError("");setSuccess("");try{for(const day of DAYS){const value=hours[day.key];if(value.enabled&&value.start>=value.end)throw new Error(`${day.label}: o horário de abertura precisa ser anterior ao fechamento.`);}const result=await neonClient.from("businesses").update({opening_hours:hours,timezone:"America/Sao_Paulo"}).eq("id",workspace.business.id);if(result.error)throw result.error;setWorkspace({...workspace,business:{...workspace.business,opening_hours:hours,timezone:"America/Sao_Paulo"}});setSuccess("Horários salvos. O agendamento público já respeita esses períodos.");}catch(reason){setError(friendlyWorkspaceError(reason));}finally{setSaving(false);}}
 if(loading)return <main className="loading"><div className="brand-mark">N</div><h1>Horários</h1><p>Carregando funcionamento...</p></main>;if(!workspace)return <main className="loading"><h1>Não foi possível abrir</h1><p>{error}</p></main>;
 return <AppShell business={workspace.business} user={workspace.user} clientCount={clientCount} memberCount={memberCount}><main className="module-content"><div className="module-head"><div><span className="eyebrow">AGENDAMENTO ONLINE</span><h1>Horários de funcionamento</h1><p>Defina quando clientes podem solicitar horários pela página pública.</p></div><a className="secondary" href="/configuracoes">← Configurações</a></div>{error?<div className="notice error">{error}</div>:null}{success?<div className="notice success">{success}</div>:null}<section className="panel" style={{maxWidth:900}}><div className="panel-head"><div><span className="eyebrow">SEMANA</span><h2>Disponibilidade padrão</h2></div></div><div className="stack">{DAYS.map(day=>{const value=hours[day.key]||DEFAULT[day.key];return <div key={day.key} style={{display:"grid",gridTemplateColumns:"minmax(150px,1fr) auto 130px 130px",gap:12,alignItems:"center",padding:"12px 0",borderBottom:"1px solid #f0f0f1"}}><strong>{day.label}</strong><label style={{display:"flex",alignItems:"center",gap:6,fontSize:12}}><input type="checkbox" checked={value.enabled} onChange={e=>patch(day.key,{enabled:e.target.checked})}/> {value.enabled?"Aberto":"Fechado"}</label><input type="time" disabled={!value.enabled} value={value.start} onChange={e=>patch(day.key,{start:e.target.value})}/><input type="time" disabled={!value.enabled} value={value.end} onChange={e=>patch(day.key,{end:e.target.value})}/></div>;})}</div><div className="notice" style={{marginTop:18}}><strong>Proteção no banco:</strong> mesmo que alguém altere o formulário público manualmente, horários fora desse período são recusados.</div><div className="form-actions"><button className="primary" onClick={()=>void save()} disabled={saving}>{saving?"Salvando...":"Salvar horários"}</button></div></section></main></AppShell>;
}
