"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { requestPasswordReset } from "@/lib/auth-password";

export default function ForgotPasswordPage(){
  const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [sent,setSent]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget);const email=String(data.get("email")||"").trim().toLocaleLowerCase("pt-BR");try{await requestPasswordReset(email,`${window.location.origin}/reset-password`);setSent(true);}catch(reason){const message=reason instanceof Error?reason.message:"";if(/network|fetch|timeout|não respondeu|indisponível|unavailable/i.test(message))setError("O serviço de autenticação não respondeu. Tente novamente.");else setSent(true);}finally{setLoading(false);}}
  return <main className="auth-page"><section className="auth-visual"><div className="auth-brand"><div className="brand-mark">N</div><div><strong>Nassus Gestão</strong><small>RECUPERAÇÃO SEGURA</small></div></div><div className="auth-copy"><span className="eyebrow">RECUPERAR ACESSO</span><h1>Volte para sua empresa sem perder nenhum dado.</h1><p>Enviaremos um link individual para redefinir sua senha. Por segurança, nunca informamos se um endereço possui conta.</p></div></section><section className="auth-side"><div className="auth-card"><div className="auth-card-mark">NG</div><span className="eyebrow">REDEFINIR SENHA</span><h2>Esqueceu sua senha?</h2><p>Informe o e-mail utilizado no Nassus Gestão.</p>{!sent?<form onSubmit={submit}><label>E-mail da conta<input name="email" type="email" required autoComplete="email" placeholder="voce@empresa.com"/></label>{error?<p className="auth-error" role="alert">{error}</p>:null}<button className="primary auth-submit" disabled={loading}>{loading?"Enviando...":"Enviar link de redefinição"}</button></form>:<div className="notice success" role="status">Se esse endereço possuir conta, o link será enviado. Verifique também Spam e Lixo eletrônico.</div>}<p className="auth-switch"><Link href="/sign-in">← Voltar para o login</Link></p></div></section></main>;
}
